import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Header from '@/components/Header';
import About from '@/components/About';
import Membership from '@/components/Membership';
import CourtBooking from '@/components/CourtBooking';
import Sponsorships from '@/components/Sponsorships';
import Blog from '@/components/Blog';
import CorporateEvents from '@/components/CorporateEvents';
import NewsLetter from '@/components/NewsLetter';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<div className='bg-gradient-to-r from-[#E7EFFF] via-white to-[#E7EFFF]'>
			<Head>
				<title>Test - Design Henge</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<Header />
			<About />
			<Membership />
			<CourtBooking />
			<Sponsorships />
			<Blog />
			<CorporateEvents />
			<NewsLetter />
		</div>
	);
}
